
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Apr 18 13:13:02 VET 2015
//----------------------------------------------------

package compilador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int OVER = 22;
  public static final int DIFERENTE = 29;
  public static final int LPAREN = 23;
  public static final int SEMI = 27;
  public static final int REPEAT = 7;
  public static final int INT = 37;
  public static final int LCORCHETE = 25;
  public static final int FOR = 28;
  public static final int MINUS = 20;
  public static final int WRITE = 10;
  public static final int RPAREN = 24;
  public static final int MENORIGUAL = 18;
  public static final int AND = 30;
  public static final int LT = 15;
  public static final int OR = 31;
  public static final int BEGIN = 5;
  public static final int UNTIL = 8;
  public static final int NUM = 12;
  public static final int PLUS = 19;
  public static final int ASSIGN = 13;
  public static final int IF = 2;
  public static final int ID = 11;
  public static final int MAYORIGUAL = 17;
  public static final int BOOLEAN = 38;
  public static final int EOF = 0;
  public static final int RETURN = 35;
  public static final int TRUE = 33;
  public static final int error = 1;
  public static final int BT = 16;
  public static final int VOID = 36;
  public static final int EQ = 14;
  public static final int TIMES = 21;
  public static final int COLON = 32;
  public static final int ELSE = 4;
  public static final int READ = 9;
  public static final int RCORCHETE = 26;
  public static final int THEN = 3;
  public static final int END = 6;
  public static final int FALSE = 34;
}

