
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Apr 18 10:55:11 VET 2015
//----------------------------------------------------

package compilador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int FUNCTION = 7;
  public static final int OVER = 34;
  public static final int GE = 28;
  public static final int SEMI = 37;
  public static final int LPAREN = 35;
  public static final int REPEAT = 15;
  public static final int LCORCH = 17;
  public static final int INT = 4;
  public static final int FOR = 19;
  public static final int MINUS = 32;
  public static final int WRITE = 21;
  public static final int RPAREN = 36;
  public static final int RCORCH = 18;
  public static final int AND = 6;
  public static final int LT = 26;
  public static final int OR = 8;
  public static final int BOOL = 2;
  public static final int BEGIN = 5;
  public static final int UNTIL = 16;
  public static final int NUM = 23;
  public static final int PLUS = 31;
  public static final int ASSIGN = 24;
  public static final int IF = 11;
  public static final int ID = 22;
  public static final int LE = 29;
  public static final int EOF = 0;
  public static final int RETURN = 9;
  public static final int error = 1;
  public static final int COMA = 10;
  public static final int NEQ = 30;
  public static final int VOID = 3;
  public static final int EQ = 25;
  public static final int TIMES = 33;
  public static final int ELSE = 13;
  public static final int READ = 20;
  public static final int THEN = 12;
  public static final int END = 14;
  public static final int GT = 27;
}

